### ISSUE TITLE
Error compiling CSS asset with 2.5.1

### ISSUE THREAD

**Issue by ghost** [mperham/sidekiq#484]
Similar to https://github.com/mperham/sidekiq/issues/481 but slightly different. After upgrading from 2.4.0 to 2.5.1 in our Rails 3.2.8 project, attempting to visit /sidekiq shows in the browser:

Error compiling CSS asset
NoMethodError: undefined method `asset_path` for #<#Class:0x007f993b5dbed0
 (in /Users/mike/.rvm/gems/ruby-1.9.3-p194@tastevin-web/gems/sidekiq-2.5.1/web/assets/stylesheets/style.scss)

/Users/mike/.rvm/gems/ruby-1.9.3-p194@tastevin-web/gems/sprockets-sass-0.9.1/lib/sprockets/sass/functions.rb:36:in `asset_path`

The Rails log shows:

Started GET "/sidekiq" for 127.0.0.1 at 2012-10-30 19:56:12 -0500
  User Load (0.7ms)  SELECT `users`.\* FROM `users` WHERE `users`.`persistence_token` = 'de97e6b309a394d2435c290b63883c7fede784fb191b273dcef5cfbe0ba4f011dd6cf19b02a86cb8afe7446fff213f9c19bbc6898455e20af17e963449b43fae' LIMIT 1

Started GET "/sidekiq/" for 127.0.0.1 at 2012-10-30 19:56:13 -0500
  User Load (0.7ms)  SELECT `users`.\* FROM `users` WHERE `users`.`persistence_token` = 'de97e6b309a394d2435c290b63883c7fede784fb191b273dcef5cfbe0ba4f011dd6cf19b02a86cb8afe7446fff213f9c19bbc6898455e20af17e963449b43fae' LIMIT 1
WARN: tilt autoloading 'sass' in a non thread-safe way; explicit require 'sass' suggested.

Started GET "/sidekiq/assets/vendors.css" for 127.0.0.1 at 2012-10-30 19:56:13 -0500
  User Load (0.7ms)  SELECT `users`.\* FROM `users` WHERE `users`.`persistence_token` = 'de97e6b309a394d2435c290b63883c7fede784fb191b273dcef5cfbe0ba4f011dd6cf19b02a86cb8afe7446fff213f9c19bbc6898455e20af17e963449b43fae' LIMIT 1

Started GET "/sidekiq/assets/application.css" for 127.0.0.1 at 2012-10-30 19:56:14 -0500
  User Load (0.8ms)  SELECT `users`.\* FROM `users` WHERE `users`.`persistence_token` = 'de97e6b309a394d2435c290b63883c7fede784fb191b273dcef5cfbe0ba4f011dd6cf19b02a86cb8afe7446fff213f9c19bbc6898455e20af17e963449b43fae' LIMIT 1

Started GET "/sidekiq/assets/application.js" for 127.0.0.1 at 2012-10-30 19:56:15 -0500
  User Load (0.8ms)  SELECT `users`.\* FROM `users` WHERE `users`.`persistence_token` = 'de97e6b309a394d2435c290b63883c7fede784fb191b273dcef5cfbe0ba4f011dd6cf19b02a86cb8afe7446fff213f9c19bbc6898455e20af17e963449b43fae' LIMIT 1

Obviously we've got all sorts of things interacting here. I'll be poking it with a stick, just passing on the data point.
