### ISSUE TITLE
Job parameters not being submitted to errbit/airbrake

### ISSUE THREAD

**Issue by davidlesches** [mperham/sidekiq#2082]
After upgrading to v3, whenever a failed job notification is sent to errbit it no longer sends the job parameters, it just sends an empty hash.

I am using an initializer with:

```
Sidekiq.configure_server do |config|
  config.error_handlers << Proc.new { |ex,ctx_hash| Airbrake.notify_or_ignore(ex, ctx_hash) }
end
```

Typical parameters I got with Sidekiq 2:

```
{
  "args" => "[\"Comment\", \"22\", \"create\"]",
  "class" => "Towncrier::Workers::Sidekiq",
  "enqueued_at" => "1418023676.6249566",
  "error_class" => "NoMethodError",
  "error_message" => "undefined method `title' for nil:NilClass",
  "failed_at" => "1418023676.6330898",
  "jid" => "ee2b6bc94e7878f9cba6d0b1",
  "queue" => "default",
  "retried_at" => "1418114783.442323",
  "retry" => "true",
  "retry_count" => "14"
}
```

Parameters I'm getting now with Sidekiq 3:

```
{
}
```
