### ISSUE TITLE
NoMethodError: undefined method `delay' 

### ISSUE THREAD

**Issue by AndydeCleyre** [mperham/sidekiq#1856]
Hi,

I'm just getting started with sidekiq, migrating a rails 3.2 project from delayed job. I tried to follow the wiki, but am still unclear on a couple of things:

1) The magic class.delay.method should work for both classes and instances, right?
2) Do I need to explicitly `require 'sidekiq'` (or include something-or-other) in various places, such as in files where I define classes (or the classes themselves) with which I want the magic .delay. to work? As it is, I only have the string "sidekiq" mentioned in the Gemfile{,.lock} and config/initializers/sidekiq.rb.
3) This will possibly be resolved based on the answers to the above questions, but my trials are failing with "<NoMethodError: undefined method `delay' for #<myclass>" -- what do I need to do to make sure that the .delay. gets properly injected?

Thank you for any pointers or assistance,

Andy

**Comment by sachin87** [comment]
@mperham  is there any way by which delay instance method to get with normal class objects(not active record)?

**Comment by mperham** [comment]
Nope. Jobs should be simple arguments, not complex stateful Ruby objects.

**Comment by codeodor** [comment]
For anyone who finds this via google: I had this issue recently and solved it with `Sidekiq::Extensions.enable_delay!` in my initializer.

**Comment by sdilshod** [comment]
Thank you @codeodor , you save me more time!

**Comment by ngouy** [comment]
thank you @codeodor, i had the same probleme switching from rails 4.x to 5.x. For people like me who are switching rails version using sidekiq inside => https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md

**Comment by rmcsharry** [comment]
I've upgraded and added Sidekiq::Extensions.enable_delay! in my initializer, but now get this error:

` NameError (undefined method `delay' for module `Kernel' Did you mean?  delay_for):
`
Any ideas?

**Comment by mperham** [comment]
Delay is not a method on everything. Classes only.

**Comment by djdarkbeat** [comment]
@codeodor This presents when upgrading Sidekiq gem from 4 to 5x
