### ISSUE TITLE
undefined method `constantize'

### ISSUE THREAD

**Issue by ihazprobs** [mperham/sidekiq#3515]
Ruby version: 2.4.0
Sidekiq / Pro / Enterprise version(s): 5.0.2 / 3.5.0 / n/a

I'm getting the following error after upgrading Sidekiq to v5.x.x:

```
2017-06-14T14:57:03.342Z 45341 TID-ov2u4lu44 WARN: {"context":"Job raised exception","job":{"class":"Sidekiq::Batch::Callback","queue":"default","args":["success","tE3kFlUqsbrCjw","default"],"retry":true,"jid":"ec0f75f8d1bd8b5ca42e5aa6","created_at":1497452223.339573,"enqueued_at":1497452223.339631}}
2017-06-14T14:57:03.342Z 45341 TID-ov2u4lu44 WARN: NoMethodError: undefined method `constantize' for "MyCallback":String
2017-06-14T14:57:03.342Z 45341 TID-ov2u4lu44 WARN: /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:19:in `execute_callback'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:32:in `block (2 levels) in success'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:31:in `each_pair'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:31:in `block in success'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:30:in `each'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:30:in `success'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/callback.rb:12:in `perform'
/Users/ihazprobs/code/gems/my_gem/test/support/sidekiq_helpers.rb:37:in `block in perform'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-pro-3.5.0/lib/sidekiq/batch/middleware.rb:33:in `call'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/ihazprobs/code/gems/my_gem/test/support/sidekiq_helpers.rb:36:in `perform'
/Users//code/gems/my_gem/test/support/sidekiq_helpers.rb:30:in `block in perform_async'
```

**Comment by mperham** [comment]
Thank you, I need to release 3.5.1 to make it work with 5.0.2.
