### ISSUE TITLE
Issue upgrading to 6.4.0 with `DelayedMailer` jobs created before deployment (v. 6.2.2)

### ISSUE THREAD

**Issue by fedetaglia** [mperham/sidekiq#5163]
Sidekiq / Pro / Enterprise version(s):
Sidekiq 6.4.0 / 5.2.4 / 2.2.3

Upgrading from `6.2.2` to `6.4.0` we experienced an issue with `Extensions::DelayedMailer`.

Arguments of jobs created with the old `6.2.2` version are missing the introduced `kwargs` and this cause a 
```undefined method `empty?' for nil:NilClass``` error.

Changes introduced in https://github.com/mperham/sidekiq/commit/0a4de94d76a07d9a61f0f55d87de79ff8bfe2f41#diff-23f1c6e4884a45dd37edb35fa76106a9c50010d94770e80076e8293c596f9b26

Wondering whether this is potentially an issue for others and should be fixed or if how we could have avoid that.

The only save way I could think of is to stop our application to create new jobs and drain the queue before deployment (not an option without a maintenance window ).

Thanks

**Comment by fedetaglia** [comment]
I can see a previews issue https://github.com/mperham/sidekiq/issues/5138 and I can see this will be [reverted](https://github.com/mperham/sidekiq/commit/cd553fa14cefe789684f3cf35b0f61e4e22b6305) in a next release.

We already got this in due to the CVE prompting a quick update.

Any concern about this breaking jobs created with those new `kwargs` ?

**Comment by mperham** [comment]
Yeah, I'm rolling that back as I think it's a bad idea to make changes to deprecated features. `main` should work the same as v6.2.2.

**Comment by fedetaglia** [comment]
👍  Thanks for the reply. I believe we can close this one, unless you want to keep it open for others to be aware of the issue until a new release is out.
