### ISSUE TITLE
Can't start, stop and then restart Sidekiq using "foreman start" / undefined method `get_sidekiq_options'

### ISSUE THREAD

**Issue by jmuheim** [mperham/sidekiq#1031]
Hey guys

I'm working on a Rails app that uses Sidekiq to import some emails in the background. After an update of Redis to 2.6, I successfully could launch the background job using `foreman start`. But I experience the problem, that when stopping foreman using Ctrl-C, I can't get the background job to run again when doing `foreman start` again - it only goes until "Starting processing, hit Ctrl-C to stop", then nothing happens anymore.

Is this a known problem? After a restart of the system it seems to be working again. Do I have to somehow shutdown Sidekiq manually so it is "really" shutdown?

Thanks for help,
Josh
