### ISSUE TITLE
Please warn about deprecation of 'log'

### ISSUE THREAD

**Issue by fuzzyalej** [mperham/sidekiq#49]
```
E, [2012-02-20T13:07:05.661890 #9710] ERROR -- : Sidekiq::Processor crashed!
NoMethodError: undefined method `log' for #<XXXX:0x00000006bcb000>
```

After updating to 0.6 we have had some troubles with log... because it is no longer available. Now we have to use `logger.debug`, etc. A warning sign would be awesome (changelog, api...)

Thank you for the work on sidekiq, it's great and the code is a pleasure to read! :D
