### ISSUE TITLE
"Failure during deserializing YAML": Sidekiq raises error when upgrading octopus gem from 0.9.0 to 0.9.2

### ISSUE THREAD

**Issue by zoonoo** [mperham/sidekiq#3855]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): Using sidekiq 5.0.5

Please include your initializer and any error message with the full backtrace.
```
Jun 01 10:56:38 app-name app/worker.1: ** [NewRelic][2018-06-01 01:56:38 +0000 worker.1 (4)] ERROR : Failure during deserializing YAML for Sidekiq::Extensions::DelayedClass
Jun 01 10:56:38 app-name app/worker.1: ** [NewRelic][2018-06-01 01:56:38 +0000 worker.1 (4)] ERROR : NoMethodError: undefined method `[]' for nil:NilClass
Jun 01 10:56:38 app-name app/worker.1: 4 TID-otgqzaygk WARN:
{"context":"Job raised exception",
 "job":{"class":"Sidekiq::Extensions::DelayedClass",
 "args":[
  "---\n
  - !ruby/class 'ReservationMobilePusher'\n
  - :request_confirm_to_guide\n
  - - !ruby/object:ETicketReservation\n
      concise_attributes:\n
          - !ruby/object:ActiveRecord::Attribute::FromDatabase\n      name: id\n value_before_type_cast: 550792\n
          - !ruby/object:ActiveRecord::Attribute::FromDatabase\n      name: begin_at\n value_before_type_cast: '2018-02-17'\n
           ...
```

```
# sidekiq.rb (initializer)
Sidekiq.configure_server do |config|
  config.redis = { url: Rails.configuration.redis_url }
end
Sidekiq.configure_client do |config|
  config.redis = { url: Rails.configuration.redis_url }
end

Sidekiq.configure_server do |_config|
  ActiveRecord::Base.establish_connection

  puts "Sidekiq process (#{Process.pid}) connection pool size is #{ActiveRecord::Base.connection_pool.instance_eval { @size }}"
end

Sidekiq::Extensions.enable_delay!

Rails.logger.warn 'Initionalize sidekiq'

```

I've left [the issue](https://github.com/thiagopradi/octopus/issues/493) in the octopus repository, but leaving it here as well to get any help I can get.

Apologies if this is not the right place to ask.

**Comment by zoonoo** [comment]
Thanks for the reply, @mperham .

The backtrace below was the actual source of the problem.

```
Jun 01 13:58:58 myrealtrip-staging app/worker.1: 4 TID-osc967f5o WARN: /app/vendor/bundle/ruby/2.3.0/gems/ar-octopus-0.9.2/lib/octopus/model.rb:50:in `init_with'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:382:in `init_with'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in `revive'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `each'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:330:in `register_empty'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/ruby-2.3.3/lib/ruby/2.3.0/psych.rb:255:in `load'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/extensions/class_methods.rb:17:in `perform'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:188:in `execute_job'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:368:in `perform_action_with_newrelic_trace'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:169:in `block in process'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:97:in `local'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:42:in `block in call'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:68:in `block in wrap'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/execution_wrapper.rb:85:in `wrap'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/reloader.rb:67:in `wrap'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/rails.rb:41:in `call'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:204:in `stats'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_logger.rb:7:in `call'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/job_retry.rb:72:in `global'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:129:in `block in dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:44:in `with_context'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:128:in `dispatch'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:168:in `process'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:85:in `process_one'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/processor.rb:73:in `run'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
Jun 01 13:58:58 myrealtrip-staging app/worker.1: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

The usual DB request from puma web server delivers Hash as the coder argument for `init_with` method on [octopus/models.rb#46](https://github.com/thiagopradi/octopus/blob/master/lib/octopus/model.rb#L46), but on Sidekiq, the argument is a Psych::Coder instance.
```
{"attributes"=>
  #<ActiveRecord::AttributeSet:0x000000096223f8
   @attributes=
    #<ActiveRecord::LazyAttributeHash:0x000000096227b8
     @additional_types={},
     @default=
      #<Proc:0x000000096227e0@/home/vagrant/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4/lib/active_record/model_schema.rb:335>,
     @delegate_hash={},
     @materialized=false,
     @types=
      {"id"=>
        #<ActiveModel::Type::Integer:0x00000008e92fe8
         @limit=nil,
         @precision=nil,
         @range=-2147483648...2147483648,
         @scale=nil>,
         ...
```
``` argument from sidekiq
#<Psych::Coder:0x0000001050f2c0
 @implicit=false,
 @map=
  {"concise_attributes"=>
    [#<ActiveRecord::Attribute::FromDatabase:0x00000010519450
      @name="id",
      @original_attribute=nil,
      @type=nil,
      @value_before_type_cast=550792>,
      ...],
   "new_record"=>false,
   "active_record_yaml_version"=>2},
 @object=nil,
 @scalar=nil,
 @seq=[],
 @style=1,
 @tag="!ruby/object:ETicketReservation",
 @type=:map>
```


It seems that the sidekiq argument is incompatible with the new octopus update. What would be the work around?

**Comment by mperham** [comment]
At a high level, your issue is that marshalling complex Ruby arguments with YAML is fraught with peril.  Reduce it to simple type arguments, as explained here:

https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple

It could be that octopus could add .to_h or other serialization helper methods to make it work with YAML but I'm not an expert in that area.  The best course is to stick with small, simple arguments.
