### ISSUE TITLE
sidekiq-ent leader lifecycle event fails on boot

### ISSUE THREAD

**Issue by rafaelsales** [mperham/sidekiq#3288]
Ruby version: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]
Sidekiq / Pro / Enterprise version(s): sidekiq (4.2.7) / sidekiq-ent (1.5.0) / sidekiq-pro (3.4.1)

I'm getting the following error on sidekiq log whenever I restart sidekiq since I upgraded to 1.5.0
```
2016-12-21T22:38:48.232Z 17017 TID-490wk INFO: Booting Sidekiq 4.2.7 with redis options {:url=>"redis://****:6379/4"}
2016-12-21T22:38:49.099Z 17017 TID-490wk INFO: Running in ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]
2016-12-21T22:38:49.100Z 17017 TID-490wk INFO: Sidekiq Pro 3.4.1 / Sidekiq Enterprise 1.5.0, commercially licensed.
2016-12-21T22:38:49.111Z 17017 TID-490wk INFO: Starting processing, hit Ctrl-C to stop
2016-12-21T22:38:49.112Z 17017 TID-ahb1g INFO: Gained leadership of the cluster
2016-12-21T22:38:49.112Z 17017 TID-afbg8 INFO: ReliableFetch activated
2016-12-21T22:38:49.121Z 17017 TID-afbg8 INFO: ReliableFetch is deprecated, super_fetch will become the new reliable_fetch in Pro 4.0.
2016-12-21T22:38:49.122Z 17017 TID-afbg8 INFO: See https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server
2016-12-21T22:38:49.129Z 17017 TID-ahb1g INFO: Managing 1 periodic jobs
2016-12-21T22:38:49.130Z 17017 TID-ahb1g WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"leader"}
2016-12-21T22:38:49.131Z 17017 TID-ahb1g WARN: NoMethodError: undefined method `split' for nil:NilClass
2016-12-21T22:38:49.132Z 17017 TID-ahb1g WARN: /var/lib/gems/2.3.0/gems/sidekiq-ent-1.5.0/lib/sidekiq-ent/census.rb:19:in `initialize'
/usr/lib/ruby/2.3.0/singleton.rb:142:in `new'
/usr/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
/usr/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
/usr/lib/ruby/2.3.0/singleton.rb:140:in `instance'
/var/lib/gems/2.3.0/gems/sidekiq-ent-1.5.0/lib/sidekiq-ent/census.rb:139:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:54:in `block in fire_event'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:52:in `each'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:52:in `fire_event'
/var/lib/gems/2.3.0/gems/sidekiq-ent-1.5.0/lib/sidekiq-ent/senate.rb:94:in `stage_coup!'
/var/lib/gems/2.3.0/gems/sidekiq-ent-1.5.0/lib/sidekiq-ent/senate.rb:100:in `cycle'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Getting this error since I upgraded to sidekiq 1.5.0

PS: Yes, I know I need to use `super_fetch!`

**Comment by mperham** [comment]
Update to 1.5.1.

**Comment by rafaelsales** [comment]
Thanks
