### ISSUE TITLE
DNS resolver locking up entire MRI process

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2175]
Several customers have reported Sidekiq "freezing" over the last 3-6 months.  When I had them put `require 'resolv-replace'` in their initializer, the problem went away.  What might cause this?

**Comment by evanphx** [comment]
If you look at the methods that are patched by `resolve-replace` you'll see all the places that might result in a hang. The hang is because those methods end up calling into libc's resolver which, if DNS is configured wrong, could block for a long time while libc waits for an answer.

**Comment by mperham** [comment]
Ok, but why would that block **all** threads on a modern MRI version?

**Comment by mperham** [comment]
If I call `TCPSocket.new("google.com", 80)`, will that block the entire process unless I use `resolv-replace`?  I tested that theory this morning by using a custom local DNS server which paused before returning a response and it did not block the process.

**Comment by mperham** [comment]
I did this:

```ruby
require 'thread'
require 'rubydns'

class MyServer < RubyDNS::Server
  def process(name, resource_class, transaction)
    sleep 3
  end
end

# Use the RubyDNS infrastructure for running the daemon:
# If asynchronous is true, it will return immediately, otherwise, it will block the current thread
 until Ctrl-C is pressed (SIGINT).
RubyDNS.run_server(asynchronous: true, server_class: MyServer)

# Directly instantiate the celluloid supervisor:
#supervisor = MyServer.supervise
#supervisor.actors.first.run

t = Thread.new do
  while true
    print '.'
    sleep 1
  end
end

Resolv.getaddress "fake.host"

t.join
```

**Comment by evanphx** [comment]
What about the `TCPSocket.connect`? Does it cause a block? There are many, many paths to code that might trigger DNS lookup in MRI.

**Comment by mperham** [comment]
There's no such method.

**Comment by mperham** [comment]
```ruby
> require 'socket'
=> true
> TCPSocket.connect
NoMethodError: undefined method `connect' for TCPSocket:Class
```

**Comment by mperham** [comment]
I can totally buy that a native gem like mysql2 or pg might call into their native client libraries which might perform a native DNS lookup without releasing the GIL.  Is that the scenario you are referring to?

**Comment by evanphx** [comment]
Er, sorry, I meant `TCPSocket.new`, like you initially indicated.

As for native gems, if that were the cause, using `resolv-replace` wouldn't fix it.

**Comment by mperham** [comment]
I'm still struggling to put together sample code which actually shows a full process lockup.  Making a bad request with Typhoeus and Curb both work fine.  TCPSocket.new works fine.

**Comment by pboling** [comment]
`resolv-replace` can actually **cause** sidekiq to freeze.  We just had a half-hour worker brown-out, shortly after upgrading from Ruby 2.7.2 to 2.7.3, caused entirely by hundreds of errors from sidekiq workers, which were all occurring in `resolve.rb`, and we have `resolv-replace` loaded in our code.

During investigation I found this: https://bugs.ruby-lang.org/issues/17781 which includes a repro that works on 2.7.3, 3.0.0, and 3.0.1 (but not 2.7.2).

```
require 'resolv'
65536.times { Resolv::DNS.new.getresource('www.example.net', Resolv::DNS::Resource::IN::A) }
puts "Ran 65536 times"
Resolv::DNS.new.getresource('www.example.net', Resolv::DNS::Resource::IN::A)
puts "Ran 65537 times" # never printed
```

I found this issue while looking to figure out a `resolve` related freeze in my app, and although it is a totally different situation, the pertinent questions are the same:

*Question 1*: Should I use `resolv-replace`?
*Answer 1*: in 2021, no. The drawbacks of `resolv-replace` are too many, and the benefits too small, if there even are any. From what I found by googling, the drawbacks are: no IPv6 support, doesn't play well with proxies, doesn't respect local `/etc/hosts` config, and it is a global override that hijacks all DNS lookups coming from Ruby, as it can't be applied discretely.

*Question 2*: How do I resolve the freeze from Ruby 2.7.3 / 3.0.0 / 3.0.1 coming from the bug in `resolv`?
*Answer 2*: I _think_ you can switch to the repo / gem library of `resolv` that [recently merged](https://github.com/ruby/resolv/pull/9) the fix:

in Gemfile:
```
gem "resolv", github: "ruby/resolv", branch: "master", ref: "c80893765dcd50e9d34b3e9dbd427cc651dc55cf"
```
and then:
```
src/api[hotfix/ENG-325-remove-resolv-replace]% bundle install
src/api[hotfix/ENG-325-remove-resolv-replace]% bundle info resolv
  * resolv (0.2.0 c808937)
	Summary: Thread-aware DNS resolver library in Ruby.
	Homepage: https://github.com/ruby/resolv
	Source Code: https://github.com/ruby/resolv
	Path: /Users/pboling/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/resolv-c80893765dcd
```

**Comment by tonywok** [comment]
@pboling Hi there, first off, thanks for the info!

For context, I'm coming to this issue after debugging a deadlocking issue described best by [New Relic's docs](https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/resque-instrumentation/#deadlocks) in which I intend to use `resolv/replace`. Your note about "not using it in 2021" is giving me pause and I want to make sure I understand what you're suggesting.

I'm a little confused by your rationale. I'm reading your suggestion as "don't use `resolv/replace`, but _do_ use `resolv` (specifically the gem with the patch instead of what ships with your ruby)".

Are you using `resolv` directly in your code? Based on my understanding of `resolv/replace`, if you don't require it, you'll be still be using Socket DNS since you've not replaced it.

**Comment by pboling** [comment]
> I'm reading your suggestion as "don't use resolv/replace, but do use resolv (specifically the gem with the patch instead of what ships with your ruby)".

Correct.

The way Ruby ships with "bundled" gems now is far different than what it used to be.

A new version of the `resolv` gem, with the fix, [has now been shipped](https://rubygems.org/gems/resolv/versions/0.2.1), but a new version of Ruby which packages it has not yet been shipped.  This means you have to add the gem you your `Gemfile` to get the fixed version.  The version that ships with Ruby 2.7.3/3.0.0/3.0.1 is broken.

When you specify the gem `resolve` in your `Gemfile` it will be automatically "required" by `bundler`, as it does all gems which do not specify `require: false`.

So to get a fixed version of the standard `resolv`, just add the gem to your `Gemfile`!  This may be what is causing your deadlock issue, if you haven't switched to the fixed `resolv` and are on Ruby v2.7.3/3.0.0/3.0.1.  I would check that before considering `resolv/replace`.

If that doesn't fix it, then it does sound like using the pure Ruby `resolve/replace` is the [best solution for the Resque/NewRelic deadlocks](https://github.com/resque/resque/issues/1101).

Just be aware of the downsides... (which I gleaned from third party sources all over the internet, not from directly understanding the source code, so could be wrong):

• no IPv6 support,
• doesn't play well with proxies,
• doesn't respect local /etc/hosts config, and
• it is a global override that hijacks all DNS lookups coming from Ruby, as it can't be applied discretely.
