### ISSUE TITLE
 undefined method `log_formatter=' for Sidekiq:Module

### ISSUE THREAD

**Issue by manjushareddy27** [mperham/sidekiq#4218]
Here is sidekiq initializer/sidekiq.rb details
Ruby version : ruby 2.4.0
Rails : 5.1.4

```
Sidekiq.configure_server do |config|
config.log_formatter = Sidekiq::Formatters::app_name.new
end

```
but it was working for below configuration 

```
Sidekiq.configure_server do |config|
config.logger.formatter = Sidekiq::Formatters::app_name.new
end
```

**Comment by Tensho** [comment]
Sorry, what is `self` for bare `config` call?

**Comment by slhck** [comment]
If anyone is getting this when upgrading to 7.x, note that the method has changed. It is not `config.logger.formatter` instead of `config.log_formatter`.
