### ISSUE TITLE
Sidekiq Pro 4.0 does not work with Sidekiq 6.1

### ISSUE THREAD

**Issue by latortuga** [mperham/sidekiq#4720]
Ruby version: 2.6.5
Rails version: 5.1.7
Sidekiq / Pro : 6.1.2 / 4.0.4

We recently bumped our sidekiq version and forgot to bump the pro gem at the same time. Bundler allowed it but it seems there's API incompatibility between these two versions. Error when starting up:

```
2020-10-19T15:37:32.852Z pid=40879 tid=owt7z4txr INFO: Loading Schedule
2020-10-19T15:37:32.852Z pid=40879 tid=owt7z4txr INFO: Schedule empty! Set Sidekiq.schedule
2020-10-19T15:37:32.852Z pid=40879 tid=owt7z4txr INFO: Schedules Loaded
2020-10-19T15:37:32.855Z pid=40879 tid=owt7z4txr INFO: Starting processing, hit Ctrl-C to stop
2020-10-19T15:37:32.855Z pid=40879 tid=owt3k2ci7 INFO: SuperFetch activated
2020-10-19T15:37:32.856Z pid=40879 tid=owt3k200n ERROR: Error fetching job: undefined method `retrieve_work' for Sidekiq::Pro::SuperFetch:Class
2020-10-19T15:37:32.857Z pid=40879 tid=owt3k200n WARN: NoMethodError: undefined method `retrieve_work' for Sidekiq::Pro::SuperFetch:Class
2020-10-19T15:37:32.857Z pid=40879 tid=owt3k200n WARN: /app/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:83:in `get_one'
```

We fixed the issue by upgrading Sidekiq Pro to 5.2.0, and maybe this isn't really something you're super worried about, but I thought we should mention just in case someone else might hit this. Might be something to note on the 4.0.x series with a patch release.

**Comment by mperham** [comment]
Yep, this is true. If you are using Sidekiq Pro or Sidekiq Enterprise, you should upgrade Sidekiq Pro or Sidekiq Enterprise. Part of that upgrade process will also upgrade Sidekiq to a version that works.

```
bundle up sidekiq-pro
bundle up sidekiq-ent
```

**Comment by mperham** [comment]
See also https://github.com/mperham/sidekiq/blob/master/Pro-5.0-Upgrade.md#upgrade
